language: node_js
node_js:
  - "11.8.0"
sudo: false
install:
  - npm install -g nyc codecov coveralls
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coverage

#notifications:
#  email: false



