language: node_js
node_js:
  - "11.8.0"
sudo: false
install:
  - npm install -g nyc codecov coveralls
script:
  - npm run coveralls
  - nyc report --reporter=text-lcov > coverage.lcov && codecov





