language: node_js
node_js:
  - "11.8.0"
sudo: false
addons:
  code_climate:
    repo_token:a50873aad72f96fe690d053c634ceb2e207d582124cb2d5d058ef621b7e2e87e
install:
  - npm install
script:
  - npm test
before_script:
  - npm install codeclimate-test-reporter nyc -g
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
  - nyc report --reporter=text-lcov | coveralls

