language: node_js
node_js:
  - "11.8.0"
sudo: false
install:
  - npm install
script:
  - npm test
  - npm install codeclimate-test-reporter istanbul -g
  - istanbul cover node_modules/mocha/bin/_mocha -- -R spec
after_script:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info




