language: node_js
node_js:
  - "11.8.0"
services: postgresql
env:
  global:
    ENV=TRAVIS
sudo: false
install:
  - npm install
  - npm install -g codecov
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm run createdb
  - npm run createAdmin
  - npm test
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
after_script:
  - npm run coverage
