language: node_js
node_js:
  - "11.8.0"
sudo: false
install:
  - npm install -g nyc codecov coveralls
script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
  - nyc ./node_modules/mocha/bin/mocha && nyc report --reporter=text-lcov | coveralls





